GET http://localhost:3000/api/product

###
# request HTTP method + URL
POST http://localhost:3000/api/cart
# Headers
Content-Type: application/json
Cookie: next-auth.session-token=3290a13f-d71f-4e84-9c77-f45df6713fc5

# body
{
    "productId": 1,
    "quantity": 1
}




