GET http://localhost:3000/api/product

###
# request HTTP method + URL
POST http://localhost:3000/api/cart
# Headers
Content-Type: application/json
Cookie: next-auth.session-token=150a69e3-c577-4147-9287-0cea494f64b4

# body
{
    "productId": 8,
    "quantity": 1
}
###
POST http://localhost:3000/api/rating
Content-Type: application/json
Cookie: next-auth.session-token=150a69e3-c577-4147-9287-0cea494f64b4

{
  "rating": 4,
  "productId": 8,
  "userId": "cltpzojya0000oh03fi97yq15"
}  

### 
GET http://localhost:3000/api/rating

###
GET http://localhost:3000/api/order
Content-Type: application/json
Cookie: next-auth.session-token=0415c621-d99e-4616-9c97-0e6dda3a899a

{
  "userId": "cltpzojya0000oh03fi97yq15"
}

###
DELETE http://localhost:3000/api/order
Content-Type: application/json
Cookie: next-auth.session-token=0415c621-d99e-4616-9c97-0e6dda3a899a

{
  "orderId": 10
}